"""
!pip install --force-reinstall --no-cache-dir tenacity==8.2.3 --user
!pip install "ibm-watsonx-ai==1.0.8" --user
!pip install "ibm-watson-machine-learning==1.0.367" --user
!pip install "langchain-ibm==0.1.7" --user
!pip install "langchain-community==0.2.10" --user
!pip install "langchain-experimental==0.0.62" --user
!pip install "langchainhub==0.1.18" --user
!pip install "langchain==0.2.11" --user
!pip install "pypdf==4.2.0" --user
!pip install "chromadb==0.4.24" --user

restart kernel
import os
os._exit(00)



Watsonx.ai provides access to several foundational models. In the previous section you used meta-llama/llama-3-3-70b-instruct. Try using another foundational model, such as ibm/granite-3-8b-instruct.

Create two instances, one instance for the Granite model and one instance for the Llama model. You can also adjust each model's creativity with different temperature settings.
Send identical prompts to each model and compare the responses.
Try at least 3 different types of prompts.

Check out these prompt types:
  Prompt type	        Prompt Example
  Creative writing   	"Write a short poem about artificial intelligence."
  Factual questions	    "What are the key components of a neural network?"
  Instruction-following	"List 5 tips for effective time management."

  Then document your observations on how temperature affects:
 - Creativity compared to consistency
 - Variation between multiple runs
 - Appropriateness for different tasks

"""
# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')
import os
os.environ['ANONYMIZED_TELEMETRY'] = 'False'

from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import ModelTypes
from ibm_watson_machine_learning.foundation_models.extensions.langchain import WatsonxLLM

credentials = {
    "url": "https://us-south.ml.cloud.ibm.com"  #This lab uses LLMs provided by Watsonx.ai.
    # "api_key": "your api key here"
    # uncomment above and fill in the API key when running locally
}

# Define different parameter sets
# Define different parameter sets
parameters_creative = {
    GenParams.MAX_NEW_TOKENS: 256,
    GenParams.TEMPERATURE: 0.8,  # Higher temperature for more creative responses
}

parameters_precise = {
    GenParams.MAX_NEW_TOKENS: 256,
    GenParams.TEMPERATURE: 0.1,  # Lower temperature for more deterministic responses
}

# Define the model ID for ibm/granite-3-3-8b-instruct
# granite='ibm/granite-3-8b-instruct'
granite='ibm/granite-3-8b-instruct'

# Define the model ID for llama-4-maverick-17b-128e-instruct-fp8
llama='meta-llama/llama-4-maverick-17b-128e-instruct-fp8'

# Create two model instances with different parameters for Granite model
granite_creative = ModelInference(
    model_id=granite,
    params=parameters_creative,
    credentials=credentials,
    project_id=project_id
)

granite_precise = ModelInference(
    model_id=granite,
    params=parameters_precise,
    credentials=credentials,
    project_id=project_id
)

# Create two model instances with different parameters for Llama model
llama_creative = ModelInference(
    model_id=llama,
    params=parameters_creative,
    credentials=credentials,
    project_id=project_id
)

llama_precise = ModelInference(
    model_id=llama,
    params=parameters_precise,
    credentials=credentials,
    project_id=project_id
)


# Wrap them for LangChain for both models
granite_llm_creative = WatsonxLLM(model=granite_creative)
granite_llm_precise = WatsonxLLM(model=granite_precise)
llama_llm_creative = WatsonxLLM(model=llama_creative)
llama_llm_precise = WatsonxLLM(model=llama_precise)

# Compare responses to the same prompt
prompts = [
    "Write a short poem about artificial intelligence",
    "What are the key components of a neural network?",
    "List 5 tips for effective time management"
]

for prompt in prompts:
    print(f"\n\nPrompt: {prompt}")
    print("\nGranite Creative response (Temperature = 0.8):")
    print(granite_llm_creative.invoke(prompt))
    print("\nLlama Creative response (Temperature = 0.8):")
    print(llama_llm_creative.invoke(prompt))
    print("\nGranite Precise response (Temperature = 0.1):")
    print(granite_llm_precise.invoke(prompt))
    print("\nLlama Precise response (Temperature = 0.1):")
    print(llama_llm_precise.invoke(prompt))